{{- $externalSecretState := dict "enabled" false -}}
{{- range .Values.tenant.secretRefs }}
{{- if or (eq .provider "vault") (eq .provider "external-secret") -}}
{{- $_ := set $externalSecretState "enabled" true -}}
{{- end -}}
{{- end -}}
{{- if and .Values.externalSecrets.enabled $externalSecretState.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ printf "%s-secrets" (include "tenant-platform.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "tenant-platform.namespace" . }}
  labels:
    {{- include "tenant-platform.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name | quote }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind | quote }}
  target:
    name: {{ include "tenant-platform.secretTargetName" . }}
    creationPolicy: Owner
  data:
    {{- range .Values.tenant.secretRefs }}
    {{- if or (eq .provider "vault") (eq .provider "external-secret") }}
    - secretKey: {{ .name | quote }}
      remoteRef:
        key: {{ .ref | quote }}
    {{- end }}
    {{- end }}
{{- end }}
