{{- if .Values.global.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tenant-platform.serviceAccountName" . }}
  namespace: {{ include "tenant-platform.namespace" . }}
  labels:
    {{- include "tenant-platform.labels" . | nindent 4 }}
  {{- if .Values.global.serviceAccount.annotations }}
  annotations:
    {{- range $key, $value := .Values.global.serviceAccount.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
